#!/bin/sh
# bootstrap-local.sh — One-command local dev setup for web-tester + web-buyer.
#
# Shared-Supabase pattern: ONE local Supabase stack on the tester ports
# (54321/54322/54323). Both tester and buyer migrations are applied to the
# same DB. The tables do not overlap.
#
# Usage:
#   chmod +x bootstrap-local.sh
#   ./bootstrap-local.sh
#
# Prerequisites: node 18+, npm, supabase CLI, Docker Desktop (running).

set -e

# ── colours ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[0;33m'; RST='\033[0m'

ok()   { printf "${GRN}[OK]${RST}   %s\n" "$1"; }
warn() { printf "${YEL}[WARN]${RST} %s\n" "$1"; }
die()  { printf "${RED}[FAIL]${RST} %s\n" "$1"; exit 1; }

# ── prerequisite checks ─────────────────────────────────────────────
printf "Checking prerequisites ...\n"

command -v node     >/dev/null 2>&1 || die "node not found. Install Node 18+."
command -v npm      >/dev/null 2>&1 || die "npm not found."
command -v supabase >/dev/null 2>&1 || die "supabase CLI not found. Install: brew install supabase/tap/supabase"
command -v docker   >/dev/null 2>&1 || die "docker not found."
docker info >/dev/null 2>&1        || die "Docker daemon is not running. Start Docker Desktop first."

NODE_MAJOR=$(node -e "process.stdout.write(String(process.versions.node.split('.')[0]))")
if [ "$NODE_MAJOR" -lt 18 ]; then
  die "Node 18+ required (found v${NODE_MAJOR})."
fi

ok "All prerequisites satisfied."

# ── paths ────────────────────────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
TESTER_DIR="${REPO_ROOT}/web-tester"
BUYER_DIR="${REPO_ROOT}/web-buyer"
SUPA_DIR="${TESTER_DIR}/supabase"

# ── start Supabase (tester project, ports 54321/54322/54323) ────────
printf "\nStarting local Supabase stack (project: oyster-gamedata-tester) ...\n"
cd "$TESTER_DIR"
supabase start 2>&1 | tail -5

ok "Supabase started on port 54321."

# ── apply buyer migrations to the SAME database ─────────────────────
printf "\nApplying buyer migrations to the shared database ...\n"

BUYER_MIGRATIONS="${BUYER_DIR}/supabase/migrations"
DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"

for f in "$BUYER_MIGRATIONS"/*.sql; do
  fname="$(basename "$f")"
  printf "  applying %s ... " "$fname"
  psql "$DB_URL" -f "$f" -q -1 2>&1 | grep -v "^$" || true
  printf "done\n"
done

ok "All buyer migrations applied."

# ── parse Supabase status for keys ──────────────────────────────────
printf "\nExtracting keys from supabase status ...\n"

cd "$TESTER_DIR"
SUPA_STATUS="$(supabase status 2>/dev/null)"

API_URL=$(printf '%s\n' "$SUPA_STATUS" | grep 'API URL' | sed 's/.*: *//')
ANON_KEY=$(printf '%s\n' "$SUPA_STATUS" | grep 'anon key' | sed 's/.*: *//')
SERVICE_ROLE_KEY=$(printf '%s\n' "$SUPA_STATUS" | grep 'service_role key' | sed 's/.*: *//')

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ] || [ -z "$SERVICE_ROLE_KEY" ]; then
  die "Failed to parse supabase status output. Raw output:\n${SUPA_STATUS}"
fi

ok "API URL:          ${API_URL}"
ok "anon key:         ${ANON_KEY}"
ok "service_role key: ${SERVICE_ROLE_KEY}" | head -c 80
printf " ...\n"

# ── generate .env.local for web-tester ──────────────────────────────
printf "\nGenerating web-tester/.env.local ...\n"
cat > "${TESTER_DIR}/.env.local" <<ENVEOF
# Auto-generated by bootstrap-local.sh — do not commit.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_TARBALL_BUCKET=tarballs
NEXT_PUBLIC_SITE_URL=http://localhost:3000
GAMEDATA_RATE_PER_HOUR_CENTS=600
GAMEDATA_MIN_PAYOUT_CENTS=2000
RECORDER_EXE_URL=https://github.com/howardleegeek/oyster-gamedata-pipeline/releases/download/recorder-v0.26.0-real-game-state/OysterRecorder.exe
RECORDER_VERSION=0.26.0
ENVEOF
ok "web-tester/.env.local written."

# ── generate .env.local for web-buyer ───────────────────────────────
printf "\nGenerating web-buyer/.env.local ...\n"
cat > "${BUYER_DIR}/.env.local" <<ENVEOF
# Auto-generated by bootstrap-local.sh — do not commit.
# Points at the SAME Supabase as web-tester (shared-stack dev pattern).
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_TARBALL_BUCKET=tarballs
NEXT_PUBLIC_SITE_URL=http://localhost:3001
GAMEDATA_PRICE_PER_GB_CENTS=2500
GAMEDATA_RESEARCH_DISCOUNT_PCT=40
DOWNLOAD_LINK_TTL_SECONDS=86400
ENVEOF
ok "web-buyer/.env.local written."

# ── npm install (idempotent) ────────────────────────────────────────
printf "\nInstalling npm dependencies ...\n"

cd "$TESTER_DIR" && npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -3
ok "web-tester: npm install done."

cd "$BUYER_DIR" && npm install --prefer-offline --no-audit --no-fund 2>&1 | tail -3
ok "web-buyer: npm install done."

# ── done ─────────────────────────────────────────────────────────────
printf "\n${GRN}=== Bootstrap complete ===${RST}\n\n"
printf "Next steps — open TWO terminals:\n"
printf "  Terminal 1:  cd web-tester && npm run dev\n"
printf "  Terminal 2:  cd web-buyer  && npm run dev\n\n"
printf "Then open:\n"
printf "  Tester portal:  http://localhost:3000\n"
printf "  Buyer portal:   http://localhost:3001\n"
printf "  Supabase Studio: http://localhost:54323\n\n"
printf "Verify with:  ./local-smoke.sh\n"
